### PR TITLE
updated to django 4 and crispy-bootstrap5

### PR DESCRIPTION
**Pull request by Nandhukriss**

### CODE REVIEW

**Comment by Nandhukriss** [comment]
was my contribution useful

**Comment by Nandhukriss** [comment]
there is a problem with django 5 which hasn't been resolved yet. I downgraded back to 4.2.5 and the logout function immediately started working again without changing any other settings.

**Comment by itsvinayak** [comment]
hi @Nandhukriss 

Thanks for the PR

**Comment by Nandhukriss** [comment]
😀✨

**Pull request merged**
